### ISSUE TITLE
没有 市  字，识别还是有问题的

### ISSUE THREAD

**Issue by mengxuande** [wzc570738205/smart_parse#11]
北京朝阳区富康路姚家园3楼

没有 市  字，识别还是有问题的！能兼容就最好拉！~~

**Comment by wzc570738205** [comment]
👌，有时间我改进下

**Comment by BaronFu** [comment]
姓名跟地址靠在一起而中间有没有分隔符这个怎么识别，
例如：北京市朝阳区富康路姚家园3楼马云150-0000-0000

**Comment by wzc570738205** [comment]
> 姓名跟地址靠在一起而中间有没有分隔符这个怎么识别，
> 例如：北京市朝阳区富康路姚家园3楼马云150-0000-0000

先根据json表切分省市区，再根据（楼，单元....自行添加）划分详细地址，剩下的就是名字和电话了

**Comment by wzc570738205** [comment]
> 姓名跟地址靠在一起而中间有没有分隔符这个怎么识别，
> 例如：北京市朝阳区富康路姚家园3楼马云150-0000-0000

![image](https://user-images.githubusercontent.com/21350874/57190268-0c3c0080-6f4b-11e9-8bdb-1f5d24887338.png)

**Comment by BaronFu** [comment]
@wzc570738205 额那假如用户没有填写你所说的这几个关键字呢？那又该如何处理

**Comment by wzc570738205** [comment]
目前不支持

**Comment by wzc570738205** [comment]
目前只支持demo列出的地址格式
