### ISSUE TITLE
这个地址有问题

### ISSUE THREAD

**Issue by CheckSkr** [wzc570738205/smart_parse#12]
苏日1853256555533  内蒙古自治区鄂尔多斯市鄂托克前旗上海庙经济开发区政府大楼100号

**Comment by wzc570738205** [comment]
已修复
![image](https://user-images.githubusercontent.com/21350874/57343194-e85c0300-7174-11e9-9629-9b23044fff69.png)
有问题请更新smart_parse/area-list.js地址列表
