### ISSUE TITLE
楼、室、等门牌号后是否可以和电话分隔识别其中的人名

### ISSUE THREAD

**Issue by Veroer** [wzc570738205/smart_parse#6]
![_20190117133838](https://user-images.githubusercontent.com/15340641/51297926-6f1d9080-1a5d-11e9-99db-3fe0ce6e246c.png)

**Comment by wzc570738205** [comment]
楼暂时没有考虑进去，我试试看

**Comment by wzc570738205** [comment]
目前只支持
1.马云,1351111111,北京市朝阳区富康路姚家园3楼

2.马云1351111111北京市朝阳区富康路姚家园3楼

3.北京市朝阳区富康路姚家园3楼1351111111马云

4.北京市朝阳区富康路姚家园3楼150-0000-0000马云

**Comment by wzc570738205** [comment]
现在已经支持！
